version: '3.7'

services:
  movie-quote-consumer:
    image: g00glen00b/movie-quote-consumer:0.0.1
    ports:
      - 8081:80
    networks:
      monitoring:
        aliases:
          - movie-quote-consumer
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
  movie-quote-consumer-prometheus:
    image: nginx/nginx-prometheus-exporter:0.2.0
    ports:
      - 9113:9113
    environment:
      - TELEMETRY_PATH=/prometheus
      - SCRAPE_URI=http://movie-quote-consumer/metrics
      - RETRIES=10
    networks:
      monitoring:
        aliases:
          - movie-quote-consumer-prometheus
  movie-quote-service:
    image: g00glen00b/movie-quote-service:0.0.2
    ports:
      - 8080:8080
    environment:
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics,prometheus
      - MANAGEMENT_ENDPOINTS_HEALTH_SHOW-DETAILS=always
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      monitoring:
        aliases:
          - movie-quote-service
  grafana:
    image: grafana/grafana:5.4.3
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus:v2.6.1
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus2.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
networks:
  monitoring:
