apiVersion: v1
kind: Service
metadata:
  name: movie-quote-api
  labels:
    app: movie-quote-app
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
  selector:
    app: movie-quote-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-quote-api
  labels:
    app: movie-quote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-quote-app
  template:
    metadata:
      labels:
        app: movie-quote-app
    spec:
      containers:
        - name: movie-quote-api
          image: g00glen00b/movie-quote-service:0.0.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
