apiVersion: v1
kind: Service
metadata:
  name: movie-quote-consumer
  labels:
    app: movie-quote-app
    tier: frontend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  selector:
    app: movie-quote-consumer
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-quote-consumer
  labels:
    app: movie-quote-app
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-quote-app
      tier: frontend
  template:
    metadata:
      labels:
        app: movie-quote-app
        tier: frontend
    spec:
      containers:
        - name: movie-quote-consumer
          image: g00glen00b/movie-quote-consumer:0.0.1
          ports:
            - containerPort: 80
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
