apiVersion: v1
kind: Service
metadata:
  name: movie-quote-consumer
  labels:
    app: movie-quote-app
    tier: frontend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: prometheus
      protocol: TCP
      port: 9113
      targetPort: 9113
  type: NodePort
  selector:
    app: movie-quote-app
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-quote-consumer
  labels:
    app: movie-quote-app
    tier: frontend
spec:
  selector:
    matchLabels:
      app: movie-quote-app
      tier: frontend
  template:
    metadata:
      labels:
        app: movie-quote-app
        tier: frontend
    spec:
      containers:
        - name: movie-quote-consumer
          image: g00glen00b/movie-quote-consumer:0.0.1
          ports:
            - containerPort: 80
              name: nginx-port
          resources:
            requests:
              memory: "32Mi"
            limits:
              memory: "64Mi"
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-config
              subPath: nginx.conf
          readinessProbe:
            httpGet:
              port: nginx-port
              path: /health
            initialDelaySeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              port: nginx-port
              path: /health
            initialDelaySeconds: 10
            timeoutSeconds: 2
        - name: movie-quote-consumer-prometheus
          image: nginx/nginx-prometheus-exporter:0.2.0
          ports:
            - containerPort: 9113
              name: exporter-port
          env:
            - name: SCRAPE_URI
              value: http://localhost/metrics
            - name: TELEMETRY_PATH
              value: /prometheus
          resources:
            requests:
              memory: "32Mi"
            limits:
              memory: "64Mi"
          readinessProbe:
            httpGet:
              port: exporter-port
              path: /prometheus
            initialDelaySeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              port: exporter-port
              path: /prometheus
            initialDelaySeconds: 10
            timeoutSeconds: 2
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config


