apiVersion: v1
kind: Service
metadata:
  name: movie-quote-consumer
  labels:
    app: movie-quote-app
    tier: frontend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
  selector:
    app: movie-quote-app
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-quote-consumer
  labels:
    app: movie-quote-app
    tier: frontend
spec:
  selector:
    matchLabels:
      app: movie-quote-app
      tier: frontend
  template:
    metadata:
      labels:
        app: movie-quote-app
        tier: frontend
    spec:
      containers:
        - name: movie-quote-consumer
          image: g00glen00b/movie-quote-consumer:0.0.1
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-config
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config

