apiVersion: v1
kind: Service
metadata:
  name: movie-quote-consumer
  labels:
    app: movie-quote-app
    tier: frontend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/prometheus"
    prometheus.io/port: "9113"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: prometheus
      port: 9113
      targetPort: 9113
  type: LoadBalancer
  selector:
    app: movie-quote-app
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-quote-consumer-deployment
spec:
  selector:
    matchLabels:
      service: movie-quote-consumer
      app: movie-quote-app
      tier: frontend
  template:
    metadata:
      labels:
        service: movie-quote-consumer
        app: movie-quote-app
        tier: frontend
    spec:
      containers:
        - name: movie-quote-consumer
          image: subhakarkotta/movie-quote-consumer:0.0.3
          ports:
            - containerPort: 80
              name: nginx-port
          resources:
            requests:
              memory: "32Mi"
            limits:
              memory: "64Mi"
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-config
              subPath: nginx.conf
          readinessProbe:
            httpGet:
              port: nginx-port
              path: /health
            initialDelaySeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              port: nginx-port
              path: /health
            initialDelaySeconds: 10
            timeoutSeconds: 2
        - name: movie-quote-consumer-prometheus
          image: nginx/nginx-prometheus-exporter:0.2.0
          ports:
            - containerPort: 9113
              name: exporter-port
          env:
            - name: SCRAPE_URI
              value: "http://localhost/metrics"
            - name: TELEMETRY_PATH
              value: "/prometheus"
            - name: NGINX_RETRIES
              value: "10"
          resources:
            requests:
              memory: "32Mi"
            limits:
              memory: "64Mi"
          readinessProbe:
            httpGet:
              port: exporter-port
              path: /prometheus
            initialDelaySeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              port: exporter-port
              path: /prometheus
            initialDelaySeconds: 10
            timeoutSeconds: 2
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config