apiVersion: v1
kind: Service
metadata:
  name: movie-quote-service
  labels:
    app: movie-quote-app
    tier: backend
spec:
  ports:
    - name: http
      nodePort: 30080
      port: 8080
  type: NodePort
  selector:
    app: movie-quote-app
    tier: backend
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-login
data:
  rootPassword: UEAkJHcwcmQK
  username: ZGJ1c2Vy
  password: ZGJwYXNz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-quote-service
  labels:
    app: movie-quote-app
    tier: backend
spec:
  selector:
    matchLabels:
      app: movie-quote-app
      tier: backend
  template:
    metadata:
      labels:
        app: movie-quote-app
        tier: backend
    spec:
      containers:
        - name: movie-quote-service
          image: g00glen00b/movie-quote-service:0.0.2
          imagePullPolicy: "Always"
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://localhost:3306/quotes?useSSL=false&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-login
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-login
                  key: password
            - name: SPRING_DATASOURCE_SCHEMA
              value: "classpath:schema-mysql.sql"
            - name: SPRING_DATASOURCE_INITIALIZATION-MODE
              value: "always"
          ports:
            - containerPort: 8080
              name: service-port
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "256Mi"
          readinessProbe:
            httpGet:
              port: service-port
              path: /actuator/health
            initialDelaySeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              port: service-port
              path: /actuator/health
            initialDelaySeconds: 30
            timeoutSeconds: 10
        - name: movie-quote-database
          image: mysql:8.0.14
          env:
            - name: MYSQL_ONETIME_PASSWORD
              value: "true"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: rootPassword
                  name: mysql-login
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mysql-login
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-login
            - name: MYSQL_DATABASE
              value: "quotes"
          ports:
            - containerPort: 3306
              name: mysql-port
          volumeMounts:
            - mountPath: /var/lib/mysql/
              name: movie-quote-storage
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "1Gi"
          livenessProbe:
            exec:
              command: ["/bin/sh", "-ec", ">-", "mysql -h127.0.0.1 -u$MYSQL_USER -p$MYSQL_PASSWORD -e'SELECT 1'"]
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["/bin/sh", "-ec", ">-", "mysql -h127.0.0.1 -u$MYSQL_USER -p$MYSQL_PASSWORD -e'SELECT 1'"]
            initialDelaySeconds: 10
            timeoutSeconds: 2
      volumes:
        - name: movie-quote-storage
          emptyDir: {}

